# Site settings
title: Weiwen Xu (Jenny)
email: wx37523@uga.com
url: https://weiwenxu21.github.io/
description: "Hey! Welcome to my website"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Weiwen Xu (Jenny)

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: wordpress
    url: https://sirjennyxu.wordpress.com/
  - title: github
    url: https://github.com/WeiwenXu21
  - title: linkedin
    url: https://www.linkedin.com/in/weiwen-xu-928122111/
  - title: instagram
    url: https://www.instagram.com/sirjennyxu/
# Build settings
markdown: kramdown
permalink: pretty
